name:                intro2fp
version:             0.1.0.0
github:              "jiftechnify/intro2fp"
license:             BSD3
author:              "jiftechnify"
maintainer:          "jiftech.stlfy@gmail.com"
copyright:           "Copyright (c) 2018 jiftechnify"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jiftechnify/intro2fp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  intro2fp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intro2fp

tests:
  intro2fp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intro2fp
